
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-vol
              mountPath: /nexus-data
      
      volumes:
       - name: nexus-vol
         persistentVolumeClaim:
           claimName: nexus-pvc
    

      nodeSelector:
         super: kolobok
      tolerations:
              - key: node-role.kubernetes.io/master
                effect: NoSchedule



---          
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: apps
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector: 
    app: nexus-server
  type: LoadBalancer  
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32081
  externalIPs:
       - 10.1.1.1     

