apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: apps
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/devops/DEVOPS/DEVOPS-KUBE-MASTER/nexus/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: apps
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
