
version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 82:80
      - 443:443
    volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf 
         - ./bublik.conf:/etc/nginx/conf.d/bublik.conf
         - ./ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
         - ./html1:/usr/share/nginx/html1
         - ./dhparam.pem://etc/nginx/dhparam.pem
         - ./ssl.key:/etc/nginx/ssl/ssl.key
         - ./ssl.crt:/etc/nginx/ssl/ssl.crt
         - ./self-signed.conf:/etc/nginx/snippets/self-signed.conf

           
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3

            
networks:
    default:
         external:
                 name: nginxbridge
              

