
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'

spec:
  selector:
    app: prometheus-server
  type: LoadBalancer
  ports:
    - port: 9090
      name: prom
      protocol: TCP
      targetPort: 9090
  externalIPs:
     - 10.1.1.1    
