apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenk-pv
  namespace: apps
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/devops/devops/jenkins/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenk-pvc
  namespace: apps
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
