apiVersion: v1
kind: PersistentVolume
metadata:
  name: jfrog-pv
  namespace: artifactory
spec:
  capacity:
    storage: 25Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/devops/jfrog/data
