
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9093'
spec:
  selector:
    app: alertmanager
  type: LoadBalancer
  ports:
    - port: 9093
      name: alertman
      targetPort: 9093
  externalIPs:
       - 10.1.1.1


